import json
import re
from llm.router import ModelRouter, AllModelsFailedError
from llm.validators import is_valid_json_object, is_non_empty_code_block
from llm.prompts import SYSTEM_PLANNING_PROMPT, SYSTEM_CODING_PROMPT
from tools.filesystem import SafeFileSystem
from models.schemas import IssueInfo, ImplementationPlan


def _extract_code_block(text: str) -> str:
    match = re.search(r"```(?:\w+)?\n(.*?)```", text, re.DOTALL)
    return match.group(1) if match else text


def _extract_json(text: str) -> str:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    return match.group(0) if match else text


class CodingAgent:
    def __init__(self, router: ModelRouter, fs: SafeFileSystem):
        self.router = router
        self.fs = fs

    def generate_plan(self, issue: IssueInfo, context: str) -> ImplementationPlan:
        prompt = f"Issue Title: {issue.title}\nIssue Body: {issue.body}\n\nCodebase Context:\n{context}"
        try:
            res, model_used = self.router.complete_with_fallback(
                "planning",
                [{"role": "system", "content": SYSTEM_PLANNING_PROMPT}, {"role": "user", "content": prompt}],
                validate_fn=is_valid_json_object,
            )
            print(f"[CodingAgent] plan generated by {model_used}")
        except AllModelsFailedError as e:
            print(f"[CodingAgent] planning failed on every model: {e}")
            return ImplementationPlan(summary="Planning failed — no models available.", files_to_modify=[], steps=[])

        try:
            data = json.loads(_extract_json(res))
            return ImplementationPlan(**data)
        except Exception:
            return ImplementationPlan(summary=res, files_to_modify=[], steps=[])
     def generate_file_patch(self, issue: IssueInfo, plan: ImplementationPlan, file_path: str,
                             already_modified: dict = None) -> str:
        try:
            current_content = self.fs.read_file(file_path)
        except FileNotFoundError:
             current_content = "(file does not exist yet — create it)"

         related_context = ""
         if already_modified:
             sections = []
             for other_path, other_content in already_modified.items():
                 # Cap each related file's contribution to keep prompt size sane
                 # on plans touching many files.
                 truncated = other_content[:2000]
                 suffix = "\n... (truncated)" if len(other_content) > 2000 else ""
                 sections.append(f"--- already modified in this plan: {other_path} ---\n{truncated}{suffix}")
             related_context = "\n\n".join(sections) + "\n\n"

         prompt = (
             f"Issue: {issue.title}\n{issue.body}\n\n"
             f"Plan summary: {plan.summary}\nSteps: {plan.steps}\n\n"
             f"{related_context}"
             f"File to modify: {file_path}\n--- current content ---\n{current_content}\n--- end ---\n\n"
             f"If any files already modified above reference or are referenced by "
             f"this file (function calls, imports, shared constants), keep this "
             f"file consistent with those changes."
         )
        try:
            res, model_used = self.router.complete_with_fallback(
                "coding",
                [{"role": "system", "content": SYSTEM_CODING_PROMPT}, {"role": "user", "content": prompt}],
                validate_fn=is_non_empty_code_block,
            )
            print(f"[CodingAgent] {file_path} patched by {model_used}")
        except AllModelsFailedError as e:
            print(f"[CodingAgent] coding failed on every model for {file_path}: {e}")
            return current_content  # leave file unchanged rather than corrupt it

        return _extract_code_block(res)

     def apply_plan(self, issue: IssueInfo, plan: ImplementationPlan) -> None:
         """
         Writes each file in the plan, sharing context of files already
         modified earlier in the same plan — so a change to auth.py can
         inform how models.py gets written right after, instead of each
         file being generated in total isolation from the others.
         """
         already_modified: dict = {}  # file_path -> new content written this run

         for file_path in plan.files_to_modify:
             new_content = self.generate_file_patch(issue, plan, file_path, already_modified)
             self.fs.write_file(file_path, new_content)
             already_modified[file_path] = new_content
             print(f"[CodingAgent] wrote {file_path} ({len(new_content)} chars)")
