import json
import re
from llm.router import ModelRouter, AllModelsFailedError
from llm.validators import is_valid_json_object, is_non_empty_code_block
from llm.prompts import SYSTEM_PLANNING_PROMPT, SYSTEM_CODING_PROMPT
from tools.filesystem import SafeFileSystem
from models.schemas import IssueInfo, ImplementationPlan


def _extract_code_block(text: str) -> str:
    match = re.search(r"```(?:\w+)?\n(.*?)```", text, re.DOTALL)
    return match.group(1) if match else text


def _extract_json(text: str) -> str:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    return match.group(0) if match else text


class CodingAgent:
    def __init__(self, router: ModelRouter, fs: SafeFileSystem):
        self.router = router
        self.fs = fs

    def generate_plan(self, issue: IssueInfo, context: str) -> ImplementationPlan:
        prompt = f"Issue Title: {issue.title}\nIssue Body: {issue.body}\n\nCodebase Context:\n{context}"
        try:
            res, model_used = self.router.complete_with_fallback(
                "planning",
                [{"role": "system", "content": SYSTEM_PLANNING_PROMPT}, {"role": "user", "content": prompt}],
                validate_fn=is_valid_json_object,
            )
            print(f"[CodingAgent] plan generated by {model_used}")
        except AllModelsFailedError as e:
            print(f"[CodingAgent] planning failed on every model: {e}")
            return ImplementationPlan(summary="Planning failed — no models available.", files_to_modify=[], steps=[])

        try:
            data = json.loads(_extract_json(res))
            return ImplementationPlan(**data)
        except Exception:
            return ImplementationPlan(summary=res, files_to_modify=[], steps=[])

    def generate_file_patch(self, issue: IssueInfo, plan: ImplementationPlan, file_path: str) -> str:
        try:
            current_content = self.fs.read_file(file_path)
        except FileNotFoundError:
            current_content = "(file does not exist yet — create it)"

        prompt = (
            f"Issue: {issue.title}\n{issue.body}\n\n"
            f"Plan summary: {plan.summary}\nSteps: {plan.steps}\n\n"
            f"File to modify: {file_path}\n--- current content ---\n{current_content}\n--- end ---"
        )
        try:
            res, model_used = self.router.complete_with_fallback(
                "coding",
                [{"role": "system", "content": SYSTEM_CODING_PROMPT}, {"role": "user", "content": prompt}],
                validate_fn=is_non_empty_code_block,
            )
            print(f"[CodingAgent] {file_path} patched by {model_used}")
        except AllModelsFailedError as e:
            print(f"[CodingAgent] coding failed on every model for {file_path}: {e}")
            return current_content  # leave file unchanged rather than corrupt it

        return _extract_code_block(res)

    def apply_plan(self, issue: IssueInfo, plan: ImplementationPlan) -> None:
        for file_path in plan.files_to_modify:
            new_content = self.generate_file_patch(issue, plan, file_path)
            self.fs.write_file(file_path, new_content)
            print(f"[CodingAgent] wrote {file_path} ({len(new_content)} chars)")
